name: Scheduled Job

on:
  schedule:
    - cron: '0 */2 * * *'     # Schedule every 2 hours
    - cron: '24 18 * * *'    # Schedule at 11:50 PM
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the desired Node.js version

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Specify the desired Python version
          

      - name: Run main2.py
        run: python main.py
        
      - name: Commit and push changes
        run: |
          git config --global user.email "abhijitgaunkerindian@gmail.com"
          git config --global user.name "AbhiGaunker"
          git add .
          git commit -m "Update files"
          git push
